### ISSUE TITLE
Change License.

### ISSUE THREAD

**Issue by xekoukou** [xekoukou/protein#7]

**Comment by sustrik** [comment]
The licensing is a bit hairy with this kind of tool.

In general, the generated code doesn't inherit the license of the tool (see gcc for example). However, if you do support "rna" files, those contain a copy of a large chunk of the original code and thus should be considered "derivative work" under GPL family of licenses IMO. You should consider whether that's what you want.

Disclaimer: I am not a lawyer.

**Comment by xekoukou** [comment]
I am changing the license of the prologue to MIT.
