### ISSUE TITLE
README still contains several references to ribosome

### ISSUE THREAD

**Issue by sustrik** [xekoukou/protein#8]
These should be replaced by protein.

Or, alternatively, we can merge the two projects to make is a single multi-language package. What do you think?

**Comment by xekoukou** [comment]
The single multilanguage project seems a better option. Feel free to merge them. Do all the changes you want.

 I don't have much time right now  to help. I am working on something else.

**Comment by sustrik** [comment]
Oops! Now I realized the licensing discrepancy. Are you committed to AGPL or would MIT/X11 works for you?

**Comment by xekoukou** [comment]
I would prefer AGPL but since this is your project after all, consider this comment as a permission to relicense xekoukou/protein under MIT/X11.

**Comment by sustrik** [comment]
Great, thanks!
